### ISSUE TITLE
Betting: I can enter a tournament without enough balance

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#12] opened 2024-08-05 22:58 UTC
**Describe the bug**
I am able to enroll and enter a tournament w/o enough
![Uploading Screenshot 2024-08-05 at 3.57.04 PM.png…]()
 balance.

**Comment by madhav-halbe** [comment] 2024-08-06 19:15
<img width="1468" alt="Screenshot 2024-08-06 at 12 15 12 PM" src="https://github.com/user-attachments/assets/1572ad64-0cbd-4a14-85c9-6ea1d67441c9">

**Comment by duck-tape** [comment] 2024-08-06 19:35
1. was the global balance also 0?
2. is this beta?

**Comment by madhav-halbe** [comment] 2024-08-06 19:38
> 1. was the global balance also 0?
> 2. is this beta?

Yes, global balance 0 and in Beta. I had tournament balance in one tournament (Around 14K), when i exited that and clicked the 2nd tournament, it showed tournament balance of 10K, when I exited that and entered the 3rd tournament, it shows a balance of "-" (As seen in the pic)

**Comment by duck-tape** [comment] 2024-08-06 19:55
What is the user_id you were using?

**Comment by madhav-halbe** [comment] 2024-08-06 20:06
madhav@sidebetz.ai

**Comment by duck-tape** [comment] 2024-08-07 18:47
@madhav-halbe Please confirm if this issue is replicable, if it is and you can provide information of the flow you used to replicate it such as 

1. Main wallet balance was "20000"
2. Entered tournament X using "10000" 
3. gamplay in tournament X
4. left tournament (did you hit leave button or click on the sidebetz logo, opened a new tab, etc)
5. Main wallet balance was "10000"
6. Entered tournament XX using "10000"
7. gameplay in tournament XX 
8. Went back to main page
9. Could enter tournament YYY even with 0 balance

**Comment by duck-tape** [comment] 2024-08-12 04:15
@madhav-halbe I am closing this for now since this is expected behavior as discussed, we can always reopen this issue if it persists after the  looping logic is dropped and new trournament behavior is live

**Closed as completed by duck-tape** 2024-08-12 04:15 UTC
Labels: BETTING
